# Day Objectives:

## File Handling :

   **File is collection of records**


- Python File Handling: Create, Open, Write,Read, Append 
    * Creating a File
    * Write the data 
    * Read data from file
    * Append data to file
    
## Modes of operation:

 * 'r'  -- Read mode which is used when the file is only being read <br>
 * 'w'  -- Write mode which is used to edit and write new information
           to the file (any existing files with the same name will be erased 
           when this mode is activated) <br>

 * 'a'  -- Appending mode, which is used to add new data to the end of the file;
           that is new information is automatically amended to the end <br>

 * 'r+' -- Special read and write mode, which is used to handle both actions 
           when working with a file
     
## In-Build function:

     * OPEN  : open(path,mode)
     * CLOSE:  file_name.close()



In [1]:
# creating a new file
book = open("sample.txt","w")
book.close()

In [2]:
# Writing data 
# syntax : open(file_path,mode)
book = open("sample.txt","w")
book.write("Hi..guys... welcome..!")
book.close()

In [3]:
# read data from sample txt file
book = open("sample.txt","r")
book.read()

'Hi..guys... welcome..!'

In [5]:
# Append Mode 
book = open("sample.txt","a")
book.write("\n very good evening everyone")
book.close()

In [6]:
data = open("fake.txt","w")
data.write("hello...!")
data.close()

In [7]:
data = open("fake.txt","w")
data.write("Nothing..! here")
data.close()

In [12]:
#r+ read and write

book = open("sample.txt","r+")
print(book.read())
book.write("\n have a nice daya Pujitha..")
book.close()

Hi..guys... welcome..!
 very good evening everyone
 have a nice daya Pujitha..
 have a nice daya Pujitha..
 have a nice daya Pujitha..


In [17]:
book = open("sample.txt","r+")
print(book.read())
book.write("\n have a nice daya Pujitha..")
book.close()


 have a nice daya Pujitha..
 have a nice daya Pujitha..


In [19]:
book = open("sample.txt","r")
print(book.readlines())

['have a nice daya Pujitha..\n', ' have a nice daya Pujitha..\n', ' have a nice daya Pujitha..\n', ' Hi..guys... welcome..!\n', ' very good evening everyone\n', ' Hi..guys... welcome..!\n', ' very good evening everyone\n', ' Hi..guys... welcome..!\n', ' very good evening everyone']


In [22]:
book = open("sample.txt","r")
for line in book.readlines():
    print(line)

have a nice daya Pujitha..

 have a nice daya Pujitha..

 have a nice daya Pujitha..

 Hi..guys... welcome..!

 very good evening everyone

 Hi..guys... welcome..!

 very good evening everyone

 Hi..guys... welcome..!

 very good evening everyone


In [23]:
book = open("sample.txt","r")
for line in book.readline():
    print(line)

h
a
v
e
 
a
 
n
i
c
e
 
d
a
y
a
 
P
u
j
i
t
h
a
.
.




In [25]:
book = open("sample.txt","a")
book.write("\n very good evening everyone")
print(book.read())
book.close()

UnsupportedOperation: not readable

In [26]:
book = open("sample.txt","r+")
book.write("\n very good evening everyone")
print(book.read())
book.close()

ave a nice daya Pujitha..
 have a nice daya Pujitha..
 Hi..guys... welcome..!
 very good evening everyone
 Hi..guys... welcome..!
 very good evening everyone
 Hi..guys... welcome..!
 very good evening everyone
 very good evening everyone
 very good evening everyone


### Task :
- create one new file
- write your details like name, ph,mail, address
- read your data
- count how many alphabets, digits, spl char


# Numpy
- Deals with numerical data
- contains n-dimensional arrays
- Numerical python is base N-dimensional array package.
* **Advantages:**
        * convenience and speed 
            * Numpy is much faster than the standard python ways to do computations
            * Can write vectorised code on numpy arrays, not on lists
            * which is convenient to read and write
            * It takes Less memory as compared to python lists 
            * Can handle the vast amount of data 

    a. Used for scientific computing and data analysis
    b. Written as ndarray (n-dimensional , homogeneous) or array
        * Commonly integers or floats
    c. Creating Numpy Arrays:
        * 1D, 2D, 3D array
        * Convert lists, tuple to np.arrays




#### Methods 
- Initialize Array:

        * np.ones(shape,dtype)
        * np.zeros(shape,dtype)
        * np.random.random(shape)
        * np.arange(start,end,step)
        * np.linspace(start,end,length of array)
        * np.full(shape,value)
        * np.tile(array,number of repetitions) or (array,shape)
        * np.eye(value,dtype) - identical matrix
        * np.random.randint(start,end,shape)
        * np.nonzero(array)
        * max,min,median,mode
        * array Transpose
        * np.vstack(array)
        * np.hstack(array
        * argsort,argmin,argmax,np.log10,pi
        
- Inspect the structure and content of array

#### numpy properties
- ndim 
     - no of dimensions of the array
- shape
     - returns the length of an array
- dtype
     - datatype of an element in an array
- size
     - returns the size of an array
- itemsize
     - returns the size of an element in bytes
     
     

In [27]:
import numpy

In [28]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [30]:
# creating numpy array by using list
import numpy as np
li = [1,2,3,4,5]
a1 = np.array(li)
type(a1)

numpy.ndarray

In [31]:
li*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [32]:
a1*2

array([ 2,  4,  6,  8, 10])

In [33]:
a1.dtype

dtype('int32')

In [34]:
a1.ndim

1

In [35]:
# 2_D array
a2 = np.array([[1,2,3,3],[2,4,56,76]])
a2

array([[ 1,  2,  3,  3],
       [ 2,  4, 56, 76]])

In [36]:
a2.ndim

2

In [37]:
a2.shape

(2, 4)

In [41]:
# 3d array
a3 = np.array([[[1,2,3,4]],[[1,2,3,4]],[[1,2,3,4]],])
a3

array([[[1, 2, 3, 4]],

       [[1, 2, 3, 4]],

       [[1, 2, 3, 4]]])

In [42]:
a3.ndim

3

In [48]:
an = np.arange(1,16)
len(an)

15

In [47]:
an.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
np.ones((5,5),dtype = "str")

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [56]:
np.zeros((3,4),dtype = "int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
np.full((4,5),"hi")

array([['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi']], dtype='<U2')

In [60]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [61]:
np.arange(1,20,10)

array([ 1, 11])

In [63]:
np.eye(5,dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [66]:
np.random.randint(1,100,10)

array([29,  5, 42, 73, 64, 43, 36, 27, 58,  1])

In [78]:
k = np.random.random(10) # 0 - 1
k

array([0.30861928, 0.9201489 , 0.65252734, 0.06814693, 0.50427083,
       0.54118632, 0.14964272, 0.29962439, 0.43047857, 0.19863167])

In [73]:
np.random.choice(["red","blue","green","yellow"])

'blue'

In [76]:
np.random.choice([1,2,3,4,5,6])

5

In [79]:
k.itemsize

8

In [80]:
k.shape

(10,)

In [81]:
k

array([0.30861928, 0.9201489 , 0.65252734, 0.06814693, 0.50427083,
       0.54118632, 0.14964272, 0.29962439, 0.43047857, 0.19863167])

In [82]:
k.size

10

In [83]:
k.ndim

1

In [85]:
len(dir(np))

622

In [86]:
k.max()

0.9201488968347412

In [87]:
k.min()

0.06814693464198007

In [89]:
k.mean()

0.4073276956335546

In [91]:
np.median(k)

0.36954892749589874

In [92]:
k+1

array([1.30861928, 1.9201489 , 1.65252734, 1.06814693, 1.50427083,
       1.54118632, 1.14964272, 1.29962439, 1.43047857, 1.19863167])

In [93]:
k*3

array([0.92585785, 2.76044669, 1.95758201, 0.2044408 , 1.5128125 ,
       1.62355896, 0.44892816, 0.89887318, 1.29143571, 0.595895  ])

# Pandas
* Which is a buildin Library and using Pandas heavily for data manipulation, visualisation, building machine learning models, etc.
* There are two main data structures in Pandas - Series and Dataframes

### The pandas Series (similar to a numpy array)

* A dataframe is simply a table where each column is a pandas series. 
    * Creating a pandas series
    * Indexing series
    
### Dataframes

* Dataframe is the most widely used data-structure in data analysis. It is a table with rows and columns, with rows having       an index and columns having meaningful names.

    * Creating dataframes from dictionaries
    * Importing CSV data files as pandas dataframes
    * Reading and summarising dataframes
    * Sorting dataframes
    

    
[Birds_dataset](https://drive.google.com/file/d/1A5Z-uNxmKLljstrX8j-1j2ydThYbe6JU/view?usp=sharing)

In [94]:
import pandas as pd

In [95]:
# list to Series
li = [12,34,45,567,6,"APSSDC"]
s1 = pd.Series(li)
s1
# havinh index value, always index starts from 0

0        12
1        34
2        45
3       567
4         6
5    APSSDC
dtype: object

In [97]:
# tuple to Series
t = (89,89,78,89.65)
s2 = pd.Series(t)
s2

0    89.00
1    89.00
2    78.00
3    89.65
dtype: float64

In [98]:
s2.index = ["a","b","c","d"]
s2

a    89.00
b    89.00
c    78.00
d    89.65
dtype: float64

In [99]:
s2[1]

89.0

In [100]:
s2[0::2]

a    89.0
c    78.0
dtype: float64

In [110]:
# Dataframe using list
li = [12,34,45,56]
l2 = [23,45,56,7]
df1 = pd.DataFrame(l2)
df1.index = ["a","b","c","d"]
df1[1] = li

In [111]:
df1

0   1
a  23  12
b  45  34
c  56  45
d   7  56

In [112]:
df1.columns

Int64Index([0, 1], dtype='int64')

In [113]:
df1.columns = ["Col1","Col2"]
df1

Col1  Col2
a    23    12
b    45    34
c    56    45
d     7    56

In [114]:
df1.shape

(4, 2)

In [115]:
df1.size

8

In [118]:
# creating DF using Dict
di = {
    "Name" : pd.Series(["Tulasi","Pujitha","Manikanta","nikhil"],index=[1,2,3,4]),
    "Branch" : pd.Series(["cse","ec","Mech"],index=[1,2,4]),
    "DOB" : pd.Series([1990,2007,2008],index = [1,3,4])
}
df2 = pd.DataFrame(di)
df2
# NAN - not a number - it's a special type of float value
# must be same length of Series and index value

Name Branch     DOB
1     Tulasi    cse  1990.0
2    Pujitha     ec     NaN
3  Manikanta    NaN  2007.0
4     nikhil   Mech  2008.0

In [121]:
type(df2["Name"])

pandas.core.series.Series

In [122]:
df2["Name"]

1       Tulasi
2      Pujitha
3    Manikanta
4       nikhil
Name: Name, dtype: object

In [124]:
df2[["Name","DOB"]] # accessing sub dataframe

Name     DOB
1     Tulasi  1990.0
2    Pujitha     NaN
3  Manikanta  2007.0
4     nikhil  2008.0

In [125]:
df2.columns

Index(['Name', 'Branch', 'DOB'], dtype='object')

In [126]:
df2.index

Int64Index([1, 2, 3, 4], dtype='int64')

In [127]:
df2.values

array([['Tulasi', 'cse', 1990.0],
       ['Pujitha', 'ec', nan],
       ['Manikanta', nan, 2007.0],
       ['nikhil', 'Mech', 2008.0]], dtype=object)

In [131]:
df2["Name"][3]

'Manikanta'

In [134]:
df2.iloc[2] # index location - accessing data 

Name      Manikanta
Branch          NaN
DOB            2007
Name: 3, dtype: object

In [137]:
df2.loc[4,"DOB"] # location

2008.0